"""Shared helper library for the WBD analysis notebooks."""

from .constants import BOXPLOT_MEANPROPS, COLOR_MAP
from .biometric import (
    BiometricHeader,
    FORM_ORDER,
    KNOWN_SENSORS,
    KNOWN_STATS,
    TITLE_FIXES,
    get_duration_differences,
    parse_biometric_header,
    reshape_biometric_long,
    summarise_biometric_structure,
)
from .imotions import (
    extract_imotions_metadata,
    read_imotions,
    read_imotions_metadata,
)
from .formatting import (
    _fmt_stat,
    format_percent,
    percentage_point_phrase,
    format_p_value,
    print_long_short_summary,
    significance_label,
    to_percent_table,
)
from .plotting import (
    annotate_boxplot_means,
    boxplot_with_means,
    register_boxplot_with_means,
)
from .categories import assign_category
from .io import safe_write_csv
from .recall_scoring import (
    SYSTEM_PROMPT_STAGE51,
    build_batch_prompt,
    call_llm_batch,
    describe_event_source,
    enrich_dataframe_with_scores,
    normalise_form,
    normalise_title,
    parse_llm_json,
    parse_model_events,
    resolve_event_list,
)
from .stats import one_tailed_p_from_paired_t
from .survey import (
    build_group_short_long_map,
    clean_response,
    clip_zero_to_four,
    derive_respondent_identifier,
    get_biometric_data,
    get_files,
    infer_group_letter,
    parse_gender,
    parse_likert_value,
    parse_recording_timestamp,
    reverse_likert,
    score_familiarity,
    score_last_watched,
)
from .uv import (
    extract_group_letter,
    extract_group_letter_from_path,
    first_segment,
    load_survey_file,
    rename_survey_columns,
)
from .recall import build_open_recall_structures

__all__ = [
    "BOXPLOT_MEANPROPS",
    "COLOR_MAP",
    "BiometricHeader",
    "SYSTEM_PROMPT_STAGE51",
    "FORM_ORDER",
    "_fmt_stat",
    "KNOWN_SENSORS",
    "KNOWN_STATS",
    "TITLE_FIXES",
    "build_batch_prompt",
    "get_duration_differences",
    "annotate_boxplot_means",
    "assign_category",
    "boxplot_with_means",
    "build_open_recall_structures",
    "build_group_short_long_map",
    "call_llm_batch",
    "clean_response",
    "clip_zero_to_four",
    "describe_event_source",
    "enrich_dataframe_with_scores",
    "extract_group_letter",
    "extract_group_letter_from_path",
    "extract_imotions_metadata",
    "derive_respondent_identifier",
    "first_segment",
    "format_percent",
    "format_p_value",
    "parse_biometric_header",
    "get_biometric_data",
    "get_files",
    "infer_group_letter",
    "load_survey_file",
    "normalise_form",
    "normalise_title",
    "one_tailed_p_from_paired_t",
    "percentage_point_phrase",
    "print_long_short_summary",
    "parse_gender",
    "parse_llm_json",
    "parse_model_events",
    "parse_recording_timestamp",
    "parse_likert_value",
    "register_boxplot_with_means",
    "reverse_likert",
    "reshape_biometric_long",
    "read_imotions",
    "read_imotions_metadata",
    "rename_survey_columns",
    "resolve_event_list",
    "score_familiarity",
    "score_last_watched",
    "safe_write_csv",
    "summarise_biometric_structure",
    "significance_label",
    "to_percent_table",
]
